### ISSUE TITLE
Unflatten ?

### ISSUE THREAD

**Issue by Oleg-dM** [ianlini/flatten-dict#2]
Hi,

Great lib, simple and powerful. I was thinking that it would be great to be able to unflatten dictionaries from flattened ones.

Cheers!

**Comment by ianlini** [comment]
Could you tell the use cases of "unflatten"?

**Comment by ianlini** [comment]
implemented in 0.0.3

**Comment by Oleg-dM** [comment]
Great thanks.
Use case is e.g. saving flattened key / value in DB then rebuidling the dictionary from DB
