### ISSUE TITLE
Feature Request: Switch "don't flatten embedded lists"

### ISSUE THREAD

**Issue by xbln** [ianlini/flatten-dict#30]
As it is usually unpredictable how many items a list will contain, it is rarely useful to flatten dictionaries which contain lists. A switch could disable flattening lists. An option could be, to assign the (unflattened) list as JSON string to the list key.

**Comment by ianlini** [comment]
I'm sorry. I didn't get it. Could you give me an example?

The default behavior of both `flatten()` and `unflatten()` doesn't do anything to the list.

**Comment by xbln** [comment]
Hi Ian,

thank you for your reply.

Here is my example:

Flattening the json object

[
{
"company": {
"name": "Miller Ltd.",
"employee": [
{
"name": "John Forster",
"department": "sales"
},
{
"name": "Bud Ryan",
"department": "finance"
},
{
"name": "Brian Walker",
"department": "sales"
}
],
"address": {
"zip": 12345,
"city": "cleveland",
"street": "255 main road"
}
}
},
{
"company": {
"name": "Mercury & Flint",
"employee": [
{
"name": "Carl Sanders",
"department": "manufactoring"
},
{
"name": "Marc Rogers",
"department": "customer service"
},
{
"name": "Glenn Scott",
"department": "sales"
}
],
"address": {
"zip": 34567,
"city": "austin",
"street": "1023 peters drive"
}
}
}
]

would result in:

[{'company_name': 'Miller Ltd.', 'company_employee_0_name': 'John Forster',
'company_employee_0_department': 'sales', 'company_employee_1_name': 'Bud
Ryan', 'company_employee_1_department': 'finance',
'company_employee_2_name': 'Brian Walker', 'company_employee_2_department':
'sales', 'company_address_zip': 12345, 'company_address_city': 'cleveland',
'company_address_street': '255 main road'}, {'company_name': 'Mercury &
Flint', 'company_employee_0_name': 'Carl Sanders',
'company_employee_0_department': 'manufactoring',
'company_employee_1_name': 'Marc Rogers', 'company_employee_1_department':
'customer service', 'company_employee_2_name': 'Glenn Scott',
'company_employee_2_department': 'sales', 'company_address_zip': 34567,
'company_address_city': 'austin', 'company_address_street': '1023 peters
drive'}]

My suggestion is, not to flatten the employee-list but keep it as
json-string. The result would be:

[{'company_name': 'Miller Ltd.', 'company_employee': '[{"name": "John
Forster", "department": "sales"}, {"name": "Bud Ryan", "department":
"finance"}, {"name": "Brian Walker", "department": "sales"}]',
'company_address_zip': 12345, 'company_address_city': 'cleveland',
'company_address_street': '255 main road'}, {'company_name': 'Mercury &
Flint', 'company_employee': '[{"name": "Carl Sanders", "department":
"manufactoring"}, {"name": "Marc Rogers", "department": "customer
service"}, {"name": "Glenn Scott", "department": "sales"}]',
'company_address_zip': 34567, 'company_address_city': 'austin',
'company_address_street': '1023 peters drive'}]


For that I made these changes to your code:

    def _flatten(d, parent=None):
        key_value_iterable = enumerate(d) if isinstance(
            d, enumerate_types) else six.viewitems(d)
        for key, value in key_value_iterable:
            flat_key = reducer(parent, key)
            if isinstance(value, flattenable_types):
                #the following 3 lines are new
                if isinstance(value, list):
                    value = json.dumps(value)
                else:
                    if value:
                        # recursively build the result
                        _flatten(value, flat_key)
                        continue
                    elif not isinstance(value, keep_empty_types):
                        # ignore the key that has an empty value
                        continue

            # add an item to the result
            if inverse:
                flat_key, value = value, flat_key
            if flat_key in flat_dict:
                raise ValueError("duplicated key '{}'".format(flat_key))
            flat_dict[flat_key] = value

Best

Martin
martin.esche@gmx.de
Mobil 0171 4103644


Am Di., 16. Juni 2020 um 05:03 Uhr schrieb Ian Lin <notifications@github.com

**Comment by ianlini** [comment]
Your expected and got results are not readable and has syntax error, and again, the default behavior is **not flattening list**. I guess you got your result by using `flatten(d, enumerate_types=(list,))`. `enumerate_types=(list,)` tells the function to flatten the list. If you explicitly tell the function to flatten the list, why do you want it not to flatten the list?

I tried to guess what you actually want to do:

```
In [2]: a
Out[2]:
[{'company': {'name': 'Miller Ltd.',
   'employee': [{'name': 'John Forster', 'department': 'sales'},
    {'name': 'Bud Ryan', 'department': 'finance'},
    {'name': 'Brian Walker', 'department': 'sales'}],
   'address': {'zip': 12345, 'city': 'cleveland', 'street': '255 main road'}}},
 {'company': {'name': 'Mercury & Flint',
   'employee': [{'name': 'Carl Sanders', 'department': 'manufactoring'},
    {'name': 'Marc Rogers', 'department': 'customer service'},
    {'name': 'Glenn Scott', 'department': 'sales'}],
   'address': {'zip': 34567,
    'city': 'austin',
    'street': '1023 peters drive'}}}]
In [7]: [flatten(d) for d in a]
Out[7]:
[{('company', 'name'): 'Miller Ltd.',
  ('company', 'employee'): [{'name': 'John Forster', 'department': 'sales'},
   {'name': 'Bud Ryan', 'department': 'finance'},
   {'name': 'Brian Walker', 'department': 'sales'}],
  ('company', 'address', 'zip'): 12345,
  ('company', 'address', 'city'): 'cleveland',
  ('company', 'address', 'street'): '255 main road'},
 {('company', 'name'): 'Mercury & Flint',
  ('company',
   'employee'): [{'name': 'Carl Sanders',
    'department': 'manufactoring'}, {'name': 'Marc Rogers', 'department': 'customer service'}, {'name': 'Glenn Scott',
    'department': 'sales'}],
  ('company', 'address', 'zip'): 34567,
  ('company', 'address', 'city'): 'austin',
  ('company', 'address', 'street'): '1023 peters drive'}]
```

**Comment by ianlini** [comment]
Closed because of no response.
Feel free to reopen it if it is still an issue.
