### ISSUE TITLE
Patch release with updated pyproject.toml?

### ISSUE THREAD

**Issue by JWCook** [ianlini/flatten-dict#40]
First of all, thanks for the handy library! I've been looking for a more lightweight alternative to `pandas.json_normalize` for awhile, and this looks like just what I needed.

Would it be possible to push out a patch release (`0.3.1`) that includes your changes to `pyproject.toml` from #32? It would be nice to have this on PyPI, because the current release installs `pathlib2` as a dependency even on python3.4+.

**Comment by ianlini** [comment]
Hi @JWCook, thanks for the reminding. I was waiting for another change but that one seems to be postponed seriously, and then I forgot to release for other changes.
I have just released 0.4.0. Please check whether this resolve the issue. Thanks.

**Comment by JWCook** [comment]
Yeah, that did it. Thanks for the quick response!
