### ISSUE TITLE
the output will remove empty dictionary.

### ISSUE THREAD

**Issue by liozzazhang** [ianlini/flatten-dict#9]
flatten_dict.py
```
# line 57
change: 
            if isinstance(value, flattenable_types):
to 
            if isinstance(value, flattenable_types) and value != {}:
```

**Comment by ianlini** [comment]
It would be clearer if we see some examples.
```python
>>> flatten({1: 2, 3: {}})
{(1,): 2}
```
I think @liozzazhang expect this result:
```
{(1,): 2, (3,): {}}
```

I actually found that it's not really a bug.
There are some cases that users actually don't want the empty values:

1. They want to use `inverse=True`:

    ```python
    >>> flatten({1: 2, 3: {}}, inverse=True)
    {2: (1,)}
    ```

    There is no way to keep the empty dict because it's not hashable.

2. They only care about those values that are not flattenable.
    This is also related to consistency. Sometimes, it's not reasonable that all other flattenable values are flattened but empty values are not. They all have the same type, but different behavior.

Though there are some problems here, keeping the empty values still make sense. It makes `flatten()` reversible in more cases.

For now, I will implement a backward-compatible version: adding a `keep_empty_types` parameters to `flatten()`. You can pass the types that you think it's reasonable to be empty in the result dict:

```python
>>> flatten({1: 2, 3: {}}, keep_empty_types=(dict,))
{(1,): 2, (3,): {}}
```

I actually struggled to make the decision. If you think keeping the empty values should be the default behavior, then give me a :confused:. If you think my proposed method is good, then give me a :+1:.
